// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: stock_trading.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StockSymbol   string                 `protobuf:"bytes,1,opt,name=stock_symbol,json=stockSymbol,proto3" json:"stock_symbol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockRequest) Reset() {
	*x = StockRequest{}
	mi := &file_stock_trading_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockRequest) ProtoMessage() {}

func (x *StockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stock_trading_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockRequest.ProtoReflect.Descriptor instead.
func (*StockRequest) Descriptor() ([]byte, []int) {
	return file_stock_trading_proto_rawDescGZIP(), []int{0}
}

func (x *StockRequest) GetStockSymbol() string {
	if x != nil {
		return x.StockSymbol
	}
	return ""
}

type StockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StockSymbol   string                 `protobuf:"bytes,1,opt,name=stock_symbol,json=stockSymbol,proto3" json:"stock_symbol,omitempty"`
	Price         float64                `protobuf:"fixed64,2,opt,name=price,proto3" json:"price,omitempty"`
	Timestamp     string                 `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockResponse) Reset() {
	*x = StockResponse{}
	mi := &file_stock_trading_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockResponse) ProtoMessage() {}

func (x *StockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stock_trading_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockResponse.ProtoReflect.Descriptor instead.
func (*StockResponse) Descriptor() ([]byte, []int) {
	return file_stock_trading_proto_rawDescGZIP(), []int{1}
}

func (x *StockResponse) GetStockSymbol() string {
	if x != nil {
		return x.StockSymbol
	}
	return ""
}

func (x *StockResponse) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *StockResponse) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type UpdateStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StockSymbol   string                 `protobuf:"bytes,1,opt,name=stock_symbol,json=stockSymbol,proto3" json:"stock_symbol,omitempty"`
	NewPrice      float64                `protobuf:"fixed64,2,opt,name=new_price,json=newPrice,proto3" json:"new_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStockRequest) Reset() {
	*x = UpdateStockRequest{}
	mi := &file_stock_trading_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStockRequest) ProtoMessage() {}

func (x *UpdateStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stock_trading_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStockRequest.ProtoReflect.Descriptor instead.
func (*UpdateStockRequest) Descriptor() ([]byte, []int) {
	return file_stock_trading_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateStockRequest) GetStockSymbol() string {
	if x != nil {
		return x.StockSymbol
	}
	return ""
}

func (x *UpdateStockRequest) GetNewPrice() float64 {
	if x != nil {
		return x.NewPrice
	}
	return 0
}

type UpdateStockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStockResponse) Reset() {
	*x = UpdateStockResponse{}
	mi := &file_stock_trading_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStockResponse) ProtoMessage() {}

func (x *UpdateStockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stock_trading_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStockResponse.ProtoReflect.Descriptor instead.
func (*UpdateStockResponse) Descriptor() ([]byte, []int) {
	return file_stock_trading_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateStockResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateStockResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CreateStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StockSymbol   string                 `protobuf:"bytes,1,opt,name=stock_symbol,json=stockSymbol,proto3" json:"stock_symbol,omitempty"`
	InitialPrice  float64                `protobuf:"fixed64,2,opt,name=initial_price,json=initialPrice,proto3" json:"initial_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateStockRequest) Reset() {
	*x = CreateStockRequest{}
	mi := &file_stock_trading_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStockRequest) ProtoMessage() {}

func (x *CreateStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stock_trading_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStockRequest.ProtoReflect.Descriptor instead.
func (*CreateStockRequest) Descriptor() ([]byte, []int) {
	return file_stock_trading_proto_rawDescGZIP(), []int{4}
}

func (x *CreateStockRequest) GetStockSymbol() string {
	if x != nil {
		return x.StockSymbol
	}
	return ""
}

func (x *CreateStockRequest) GetInitialPrice() float64 {
	if x != nil {
		return x.InitialPrice
	}
	return 0
}

type CreateStockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateStockResponse) Reset() {
	*x = CreateStockResponse{}
	mi := &file_stock_trading_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStockResponse) ProtoMessage() {}

func (x *CreateStockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stock_trading_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStockResponse.ProtoReflect.Descriptor instead.
func (*CreateStockResponse) Descriptor() ([]byte, []int) {
	return file_stock_trading_proto_rawDescGZIP(), []int{5}
}

func (x *CreateStockResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateStockResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_stock_trading_proto protoreflect.FileDescriptor

const file_stock_trading_proto_rawDesc = "" +
	"\n" +
	"\x13stock_trading.proto\x12\fstocktrading\"1\n" +
	"\fStockRequest\x12!\n" +
	"\fstock_symbol\x18\x01 \x01(\tR\vstockSymbol\"f\n" +
	"\rStockResponse\x12!\n" +
	"\fstock_symbol\x18\x01 \x01(\tR\vstockSymbol\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x01R\x05price\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\tR\ttimestamp\"T\n" +
	"\x12UpdateStockRequest\x12!\n" +
	"\fstock_symbol\x18\x01 \x01(\tR\vstockSymbol\x12\x1b\n" +
	"\tnew_price\x18\x02 \x01(\x01R\bnewPrice\"I\n" +
	"\x13UpdateStockResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\\\n" +
	"\x12CreateStockRequest\x12!\n" +
	"\fstock_symbol\x18\x01 \x01(\tR\vstockSymbol\x12#\n" +
	"\rinitial_price\x18\x02 \x01(\x01R\finitialPrice\"I\n" +
	"\x13CreateStockResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\x8c\x02\n" +
	"\x13StockTradingService\x12H\n" +
	"\rgetStockPrice\x12\x1a.stocktrading.StockRequest\x1a\x1b.stocktrading.StockResponse\x12W\n" +
	"\x10updateStockPrice\x12 .stocktrading.UpdateStockRequest\x1a!.stocktrading.UpdateStockResponse\x12R\n" +
	"\vcreateStock\x12 .stocktrading.CreateStockRequest\x1a!.stocktrading.CreateStockResponseB|\n" +
	"\x13com.javatechie.grpcB\x11StockTradingProtoP\x01ZPgithub.com/JeroZp/gRPC-MOM/API-Gateway/internal/stock_trading_server/proto;protob\x06proto3"

var (
	file_stock_trading_proto_rawDescOnce sync.Once
	file_stock_trading_proto_rawDescData []byte
)

func file_stock_trading_proto_rawDescGZIP() []byte {
	file_stock_trading_proto_rawDescOnce.Do(func() {
		file_stock_trading_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stock_trading_proto_rawDesc), len(file_stock_trading_proto_rawDesc)))
	})
	return file_stock_trading_proto_rawDescData
}

var file_stock_trading_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_stock_trading_proto_goTypes = []any{
	(*StockRequest)(nil),        // 0: stocktrading.StockRequest
	(*StockResponse)(nil),       // 1: stocktrading.StockResponse
	(*UpdateStockRequest)(nil),  // 2: stocktrading.UpdateStockRequest
	(*UpdateStockResponse)(nil), // 3: stocktrading.UpdateStockResponse
	(*CreateStockRequest)(nil),  // 4: stocktrading.CreateStockRequest
	(*CreateStockResponse)(nil), // 5: stocktrading.CreateStockResponse
}
var file_stock_trading_proto_depIdxs = []int32{
	0, // 0: stocktrading.StockTradingService.getStockPrice:input_type -> stocktrading.StockRequest
	2, // 1: stocktrading.StockTradingService.updateStockPrice:input_type -> stocktrading.UpdateStockRequest
	4, // 2: stocktrading.StockTradingService.createStock:input_type -> stocktrading.CreateStockRequest
	1, // 3: stocktrading.StockTradingService.getStockPrice:output_type -> stocktrading.StockResponse
	3, // 4: stocktrading.StockTradingService.updateStockPrice:output_type -> stocktrading.UpdateStockResponse
	5, // 5: stocktrading.StockTradingService.createStock:output_type -> stocktrading.CreateStockResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_stock_trading_proto_init() }
func file_stock_trading_proto_init() {
	if File_stock_trading_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stock_trading_proto_rawDesc), len(file_stock_trading_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_stock_trading_proto_goTypes,
		DependencyIndexes: file_stock_trading_proto_depIdxs,
		MessageInfos:      file_stock_trading_proto_msgTypes,
	}.Build()
	File_stock_trading_proto = out.File
	file_stock_trading_proto_goTypes = nil
	file_stock_trading_proto_depIdxs = nil
}
