// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: stock_trading.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StockTradingService_GetStockPrice_FullMethodName    = "/stocktrading.StockTradingService/getStockPrice"
	StockTradingService_UpdateStockPrice_FullMethodName = "/stocktrading.StockTradingService/updateStockPrice"
	StockTradingService_CreateStock_FullMethodName      = "/stocktrading.StockTradingService/createStock"
)

// StockTradingServiceClient is the client API for StockTradingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StockTradingServiceClient interface {
	// UNARY - RPC -> get current stock price
	GetStockPrice(ctx context.Context, in *StockRequest, opts ...grpc.CallOption) (*StockResponse, error)
	// UNARY - RPC -> update stock price
	UpdateStockPrice(ctx context.Context, in *UpdateStockRequest, opts ...grpc.CallOption) (*UpdateStockResponse, error)
	// UNARY - RPC -> create a new stock
	CreateStock(ctx context.Context, in *CreateStockRequest, opts ...grpc.CallOption) (*CreateStockResponse, error)
}

type stockTradingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStockTradingServiceClient(cc grpc.ClientConnInterface) StockTradingServiceClient {
	return &stockTradingServiceClient{cc}
}

func (c *stockTradingServiceClient) GetStockPrice(ctx context.Context, in *StockRequest, opts ...grpc.CallOption) (*StockResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StockResponse)
	err := c.cc.Invoke(ctx, StockTradingService_GetStockPrice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stockTradingServiceClient) UpdateStockPrice(ctx context.Context, in *UpdateStockRequest, opts ...grpc.CallOption) (*UpdateStockResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateStockResponse)
	err := c.cc.Invoke(ctx, StockTradingService_UpdateStockPrice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stockTradingServiceClient) CreateStock(ctx context.Context, in *CreateStockRequest, opts ...grpc.CallOption) (*CreateStockResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateStockResponse)
	err := c.cc.Invoke(ctx, StockTradingService_CreateStock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StockTradingServiceServer is the server API for StockTradingService service.
// All implementations must embed UnimplementedStockTradingServiceServer
// for forward compatibility.
type StockTradingServiceServer interface {
	// UNARY - RPC -> get current stock price
	GetStockPrice(context.Context, *StockRequest) (*StockResponse, error)
	// UNARY - RPC -> update stock price
	UpdateStockPrice(context.Context, *UpdateStockRequest) (*UpdateStockResponse, error)
	// UNARY - RPC -> create a new stock
	CreateStock(context.Context, *CreateStockRequest) (*CreateStockResponse, error)
	mustEmbedUnimplementedStockTradingServiceServer()
}

// UnimplementedStockTradingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStockTradingServiceServer struct{}

func (UnimplementedStockTradingServiceServer) GetStockPrice(context.Context, *StockRequest) (*StockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStockPrice not implemented")
}
func (UnimplementedStockTradingServiceServer) UpdateStockPrice(context.Context, *UpdateStockRequest) (*UpdateStockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateStockPrice not implemented")
}
func (UnimplementedStockTradingServiceServer) CreateStock(context.Context, *CreateStockRequest) (*CreateStockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateStock not implemented")
}
func (UnimplementedStockTradingServiceServer) mustEmbedUnimplementedStockTradingServiceServer() {}
func (UnimplementedStockTradingServiceServer) testEmbeddedByValue()                             {}

// UnsafeStockTradingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StockTradingServiceServer will
// result in compilation errors.
type UnsafeStockTradingServiceServer interface {
	mustEmbedUnimplementedStockTradingServiceServer()
}

func RegisterStockTradingServiceServer(s grpc.ServiceRegistrar, srv StockTradingServiceServer) {
	// If the following call pancis, it indicates UnimplementedStockTradingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StockTradingService_ServiceDesc, srv)
}

func _StockTradingService_GetStockPrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StockTradingServiceServer).GetStockPrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StockTradingService_GetStockPrice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StockTradingServiceServer).GetStockPrice(ctx, req.(*StockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StockTradingService_UpdateStockPrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateStockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StockTradingServiceServer).UpdateStockPrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StockTradingService_UpdateStockPrice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StockTradingServiceServer).UpdateStockPrice(ctx, req.(*UpdateStockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StockTradingService_CreateStock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateStockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StockTradingServiceServer).CreateStock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StockTradingService_CreateStock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StockTradingServiceServer).CreateStock(ctx, req.(*CreateStockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StockTradingService_ServiceDesc is the grpc.ServiceDesc for StockTradingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StockTradingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "stocktrading.StockTradingService",
	HandlerType: (*StockTradingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getStockPrice",
			Handler:    _StockTradingService_GetStockPrice_Handler,
		},
		{
			MethodName: "updateStockPrice",
			Handler:    _StockTradingService_UpdateStockPrice_Handler,
		},
		{
			MethodName: "createStock",
			Handler:    _StockTradingService_CreateStock_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "stock_trading.proto",
}
